name: KMM Bridge Github Workflow
on:
  workflow_call:
    inputs:
      KMM_MODULE_PATH:
        type: string
        required: true
    secrets:
      gradle_params:
        required: false

jobs:
  kmmbridgepublish:
    concurrency: "kmmbridgepublish-${{ github.repository }}"
    runs-on: macos-latest
    steps:
      - name: Random ID for build branch
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1
      - uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "build-${{ steps.generate-uuid.outputs.uuid }}"
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          ref: "build-${{ steps.generate-uuid.outputs.uuid }}"
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Cache build tooling
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.konan
          key: ${{ runner.os }}-v4-${{ hashFiles('*.gradle.kts') }}
      - name: Build Main
        run: ./gradlew publishRemoteFramework -PGITHUB_PUBLISH_TOKEN=${{ secrets.GITHUB_TOKEN }} -PGITHUB_REPO=${{ github.repository }} ${{ secrets.gradle_params }} --no-daemon --stacktrace
        env:
          GRADLE_OPTS: -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=512m"
      - name: Push Config Updates
        uses: touchlab/git-auto-commit-action@v4
        with:
          commit_message: Update iOS Packaging
      - name: Read version
        id: version
        uses: touchlab/read-file-action@v1
        with:
          path: "${{ inputs.KMM_MODULE_PATH }}/build/faktory/version"
      - name: Create Release
        uses: touchlab/release-action@v1.10.0
        with:
          commit: "build-${{ steps.generate-uuid.outputs.uuid }}"
          tag: ${{ steps.version.outputs.content }}
      - name: Delete branch
        uses: touchlab/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: "build-${{ steps.generate-uuid.outputs.uuid }}"